### ISSUE TITLE
Build docs as part of Travis CI tests

### ISSUE THREAD

**Issue by Abscissa** [mysql-d/mysql-native#181]
...to ensure doc-building doesn't get broken.

**Comment by SingingBush** [comment]
now that github actions are used the title of this issue needs renaming. It's still needed however. I recommend making a new workflow for building the documentation that get's run whenever a tag is created, something like:

```yaml
name: Build Documentation

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      ...
```

I didn't do this as part of #227 but it should be fairly straight forward
