### ISSUE TITLE
Column 22 is null, check for isNull

### ISSUE THREAD

**Issue by bhechinger** [mysql-d/mysql-native#51]
I am having this issue mysql on a database:

```
mysql.common.MySQLException@../../.dub/packages/mysql-native-master/source/mysql/result.d(176): Column 22 is null, check for isNull
```

What should I be looking for?

```
*************************** 22. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: eve_static
              TABLE_NAME: mapsolarsystems
             COLUMN_NAME: security
        ORDINAL_POSITION: 22
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: double
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 22
           NUMERIC_SCALE: NULL
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: double
              COLUMN_KEY: MUL
                   EXTRA:
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT:
```

Mysql Version:
`mysql  Ver 14.14 Distrib 5.6.20, for osx10.9 (x86_64) using  EditLine wrapper`

mysql-native Version:
Uhm, not sure. I'm using dub to pull ~master but I don't have your NEWDECIMAL patch, so it's hard to say exactly. Unless you can tell me how to determine better.
