### ISSUE TITLE
please consider setting up travis build

### ISSUE THREAD

**Issue by SingingBush** [mysql-d/mysql-native#73]
it's worth having some kind of automated build process. travis-ci.org has decent support for D. The following `.travis.yml` will be enough to build with dmd, ldc, and gdc on both Linux and OSX:

```yml
language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.068.0
  - ldc-1.0.0-beta2
  - gdc

os:
 - linux
 - osx

matrix:
  allow_failures:
    - d: gdc
```
